title: "Akshay Pujari"
author: "Akshay Pujari"
email: "akshaypujari013@gmail.com"
description: "Personal website and portfolio of Akshay Pujari"

url: "https://akshaypujari.github.io"
baseurl: "" # Important for user/organization GitHub Pages

timezone: "America/Los_Angeles"

markdown: kramdown
theme: null
permalink: pretty

sass:
  sass_dir: assets/_scss
  style: compressed

collections:
  publications:
    output: true
    permalink: /publications/:title/
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: publication
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

social_links:
  github: https://github.com/akshaypujari
  linkedin: https://www.linkedin.com/in/akshaypujari/
  twitter: https://twitter.com/el_akshay

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - google*.html
