title: "Akshay Pujari"
email: "akshaypujari013@gmail.com"
author: "Akshay Pujari"
description: "Personal website and portfolio of Akshay Pujari – Data Scientist, Software Engineer, and Bioinformatician."

baseurl: "" # for GitHub Pages root
url: "https://akshaypujari.github.io"
timezone: "America/Los_Angeles"

collections:
  publications:
    output: true
    permalink: /publications/:title/
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: publication
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

sass:
  sass_dir: assets/_scss
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

social_links:
  github: https://github.com/akshaypujari
  linkedin: https://www.linkedin.com/in/akshaypujari/
  twitter: https://twitter.com/el_akshay

markdown: kramdown
theme: null

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - google*.html

permalink: pretty